name: mayr_extensions
description: A comprehensive set of handy Dart and Flutter extensions to make your code cleaner, shorter, and more expressive.
version: 1.0.1
homepage: https://github.com/YoungMayor/flutter_utils_extensions
repository: https://github.com/YoungMayor/flutter_utils_extensions
issue_tracker: https://github.com/YoungMayor/flutter_utils_extensions/issues
documentation: https://github.com/YoungMayor/flutter_utils_extensions/wiki
license: MIT

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_time_ago: ^2.3.0
  intl: '>=0.18.0 <0.21.0'
  xml: ^6.5.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - extensions
  - utilities
  - flutter
  - productivity
  - toolkit
